# Generated by Django 4.2.7 on 2023-12-22 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, upload_to='horarios/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horarios.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=200)),
                ('nombre_padre', models.CharField(max_length=200)),
                ('correo_padre', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('seccion_estudiante', models.ManyToManyField(to='Registro_Ausencias.secciones')),
            ],
        ),
    ]
