# Generated by Django 4.2.7 on 2023-12-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255)),
                ('cedu_estudiante', models.IntegerField()),
                ('nacionalidad_estudiante', models.CharField(max_length=255)),
                ('fecha_estudiante', models.DateField(max_length=255)),
                ('correo_estudiante', models.EmailField(max_length=254)),
                ('sexo_estudiante', models.CharField(max_length=255)),
                ('colegio_procedencia', models.CharField(max_length=100)),
                ('repitencia', models.CharField(max_length=10)),
                ('especialidades', models.CharField(max_length=500)),
                ('especialidadFavorita', models.CharField(max_length=255)),
                ('nombre_padre', models.CharField(max_length=255)),
                ('cedu_padre', models.IntegerField()),
                ('nacionalidad_padre', models.CharField(max_length=255)),
                ('sexo_padre', models.CharField(max_length=255)),
                ('telefono_padre', models.IntegerField()),
                ('correo_padre', models.EmailField(max_length=254)),
                ('ocupacion_padre', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prematricula',
                'verbose_name_plural': 'Prematriculas',
            },
        ),
        migrations.CreateModel(
            name='Tecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
