# Generated by Django 4.2.8 on 2024-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prematricula',
            name='cedu_estudiante',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='prematricula',
            name='cedu_padre',
            field=models.BigIntegerField(),
        ),
    ]
