# Generated by Django 4.2.8 on 2024-01-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_alter_prematricula_cedu_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='showPrematricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'showPrematricula',
                'verbose_name_plural': 'showPrematriculas',
            },
        ),
    ]
